align_assignment = false
align_conditional = false
align_matrix = false
align_pair_arrow = false
align_struct_field = false
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = true
conditional_to_if = true
disallow_single_arg_nesting = false
for_in_replacement = "in"
force_long_function_def = true
format_docstrings = true
format_markdown = true
import_to_using = false
indent_submodule = true
join_lines_based_on_source = false
long_to_short_function_def = false
max_iterations = 10
normalize_line_endings = "unix"
overwrite = true
pipe_to_function_call = true
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_circuit_to_if = true
short_to_long_function_def = true
surround_whereop_typeparameters = true
trailing_comma = true
trailing_zero = true
transform_syntax_in_macros = true
v2_stable_multiline_strings = true
verbose = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
