name: CI
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
      branches:
        - main
      tags:
        - v*
  pull_request:
  release:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        group:
          - CheckByAqua
          - CheckByJET
          - CheckByExplicitImports
        version:
          - release
          - lts
          - nightly
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      # - uses: julia-actions/julia-uploadcoveralls@v1
      #   env:
      #     COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
