name: Formatter
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    tags: ['*']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: 'release'
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter and format
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.add(["JuliaFormatter", "Runic"])
          import JuliaFormatter, Runic
          JuliaFormatter.format(".")
          Runic.main(["--inplace", "."])
          JuliaFormatter.format(".")
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format .jl files
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
